"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-2jt$!%j9*hebv+mb_ec=l^fx=&l$2u#n^%@z!rxkeu#38j=o*j')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

def split_env_list(value: str):
    return [item.strip() for item in value.split(',') if item.strip()]


DEFAULT_ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.railway.app']
DEFAULT_CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'http://localhost:4200',
    'http://127.0.0.1:4200',
]
DEFAULT_CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',
    'http://127.0.0.1:4200',
]

ALLOWED_HOSTS = split_env_list(os.environ.get('ALLOWED_HOSTS', '')) or (['*'] if DEBUG else DEFAULT_ALLOWED_HOSTS)
CSRF_TRUSTED_ORIGINS = split_env_list(os.environ.get('CSRF_TRUSTED_ORIGINS', '')) or DEFAULT_CSRF_TRUSTED_ORIGINS

CORS_ALLOWED_ORIGINS = split_env_list(os.environ.get('CORS_ALLOWED_ORIGINS', '')) or DEFAULT_CORS_ALLOWED_ORIGINS
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True' if DEBUG else 'False') == 'True'

if not DEBUG:
    # Seguridad HTTPS en Produccion
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 anio
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',

    # --- TUS APPS (ESTO FALTABA) ---
    'core',
    'pedidos',
    'pos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoise para archivos estaticos
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_L10N = False  # Forzar punto decimal (USD) en vez de coma espaniola
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- EMAIL (FACTURA ELECTRONICA) ---
# En desarrollo (DEBUG=True): imprime en consola si no hay credenciales SMTP.
# En producción (DEBUG=False): usa SMTP automáticamente.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST          = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT          = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS       = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.environ.get('DEFAULT_FROM_EMAIL', f'RAMON by Bosco <{EMAIL_HOST_USER}>')

# --- INTEGRACIONES WHATSAPP / ASYNC ---
WHATSAPP_PROVIDER = os.environ.get('WHATSAPP_PROVIDER', 'TWILIO').upper()
PUBLIC_PWA_URL = os.environ.get('PUBLIC_PWA_URL', 'http://127.0.0.1:4200')
PUBLIC_BACKEND_URL = os.environ.get('PUBLIC_BACKEND_URL', 'http://127.0.0.1:8000')
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
TWILIO_WHATSAPP_NUMBER = os.environ.get('TWILIO_WHATSAPP_NUMBER', '')
TWILIO_CONFIRM_TEMPLATE_SID = os.environ.get('TWILIO_CONFIRM_TEMPLATE_SID', '')
TWILIO_SIGNATURE_VALIDATION = os.environ.get('TWILIO_SIGNATURE_VALIDATION', 'False' if DEBUG else 'True') == 'True'
META_WHATSAPP_TOKEN = os.environ.get('META_WHATSAPP_TOKEN', '')
META_WHATSAPP_PHONE_NUMBER_ID = os.environ.get('META_WHATSAPP_PHONE_NUMBER_ID', '')
META_WHATSAPP_API_VERSION = os.environ.get('META_WHATSAPP_API_VERSION', 'v22.0')
META_WHATSAPP_VERIFY_TOKEN = os.environ.get('META_WHATSAPP_VERIFY_TOKEN', '')
META_WHATSAPP_APP_SECRET = os.environ.get('META_WHATSAPP_APP_SECRET', '')
META_SIGNATURE_VALIDATION = os.environ.get('META_SIGNATURE_VALIDATION', 'False' if DEBUG else 'True') == 'True'
DELIVERY_QUOTE_TIMEOUT_SECONDS = int(os.environ.get('DELIVERY_QUOTE_TIMEOUT_SECONDS', '180'))
DELIVERY_QUOTE_TOKEN_MAX_AGE_SECONDS = int(os.environ.get('DELIVERY_QUOTE_TOKEN_MAX_AGE_SECONDS', '900'))

REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', REDIS_URL)
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 20 * 60
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'True' if DEBUG else 'False') == 'True'


WHATSAPP_WEBHOOK_VERIFY = os.environ.get('WHATSAPP_WEBHOOK_VERIFY', '')
WHATSAPP_INBOUND_RATE_LIMIT_WINDOW_SECONDS = int(
    os.environ.get('WHATSAPP_INBOUND_RATE_LIMIT_WINDOW_SECONDS', '60')
)
WHATSAPP_INBOUND_RATE_LIMIT_MAX = int(os.environ.get('WHATSAPP_INBOUND_RATE_LIMIT_MAX', '20'))
PRINT_JOB_STUCK_SECONDS = int(os.environ.get('PRINT_JOB_STUCK_SECONDS', '120'))

# --- OPERACION / HORARIO ---
# En desarrollo se desactiva por defecto para facilitar pruebas.
# En produccion se activa por defecto.
ENABLE_BUSINESS_HOURS = os.environ.get('ENABLE_BUSINESS_HOURS', 'False' if DEBUG else 'True') == 'True'

