"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-2jt$!%j9*hebv+mb_ec=l^fx=&l$2u#n^%@z!rxkeu#38j=o*j')

# SECURITY WARNING: don't run with debug turned on in production!
ON_RAILWAY = bool(os.environ.get('RAILWAY_ENVIRONMENT'))
DEBUG = False if ON_RAILWAY else os.environ.get('DEBUG', 'True') == 'True'

def split_env_list(value: str):
    return [item.strip() for item in value.split(',') if item.strip()]


DEFAULT_ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '.railway.app']
DEFAULT_CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'http://localhost:4200',
    'http://127.0.0.1:4200',
]
DEFAULT_CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',
    'http://127.0.0.1:4200',
]

ALLOWED_HOSTS = split_env_list(os.environ.get('ALLOWED_HOSTS', '')) or (['*'] if DEBUG else DEFAULT_ALLOWED_HOSTS)
CSRF_TRUSTED_ORIGINS = split_env_list(os.environ.get('CSRF_TRUSTED_ORIGINS', '')) or DEFAULT_CSRF_TRUSTED_ORIGINS

CORS_ALLOWED_ORIGINS = split_env_list(os.environ.get('CORS_ALLOWED_ORIGINS', '')) or DEFAULT_CORS_ALLOWED_ORIGINS
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True' if DEBUG else 'False') == 'True'

if not DEBUG:
    # Seguridad HTTPS en Produccion
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 anio
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',

    # --- TUS APPS (ESTO FALTABA) ---
    'core',
    'pedidos',
    'pos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoise para archivos estaticos
    'corsheaders.middleware.CorsMiddleware',
    'pos.middleware.CorrelationIdMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'pos.middleware.LedgerRegistryFenceMiddleware',
    'pos.middleware.LocationContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_L10N = False  # Forzar punto decimal (USD) en vez de coma espaniola
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- EMAIL (FACTURA ELECTRONICA) ---
# En desarrollo (DEBUG=True): imprime en consola si no hay credenciales SMTP.
# En producción (DEBUG=False): usa SMTP automáticamente.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG
    else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST          = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT          = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS       = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER     = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL  = os.environ.get('DEFAULT_FROM_EMAIL', f'RAMON by Bosco <{EMAIL_HOST_USER}>')
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
RESEND_API_BASE = os.environ.get('RESEND_API_BASE', 'https://api.resend.com')
RESEND_API_TIMEOUT_SECONDS = int(os.environ.get('RESEND_API_TIMEOUT_SECONDS', '15'))

# --- INTEGRACIONES WHATSAPP / ASYNC ---
PUBLIC_PWA_URL = os.environ.get('PUBLIC_PWA_URL', 'http://127.0.0.1:4200')
PUBLIC_BACKEND_URL = os.environ.get('PUBLIC_BACKEND_URL', 'http://127.0.0.1:8000')
META_WHATSAPP_TOKEN = os.environ.get('META_WHATSAPP_TOKEN', '')
META_WHATSAPP_PHONE_NUMBER_ID = os.environ.get('META_WHATSAPP_PHONE_NUMBER_ID', '')
META_WHATSAPP_API_VERSION = os.environ.get('META_WHATSAPP_API_VERSION', 'v22.0')
META_WHATSAPP_VERIFY_TOKEN = os.environ.get('META_WHATSAPP_VERIFY_TOKEN', '')
META_WHATSAPP_APP_SECRET = os.environ.get('META_WHATSAPP_APP_SECRET', '')
META_SIGNATURE_VALIDATION = os.environ.get('META_SIGNATURE_VALIDATION', 'False' if DEBUG else 'True') == 'True'
DELIVERY_QUOTE_TIMEOUT_SECONDS = int(os.environ.get('DELIVERY_QUOTE_TIMEOUT_SECONDS', '180'))
DELIVERY_QUOTE_TOKEN_MAX_AGE_SECONDS = int(os.environ.get('DELIVERY_QUOTE_TOKEN_MAX_AGE_SECONDS', '900'))

# --- TELEGRAM BOT (NOTIFICACION GRUPO REPARTIDORES) ---
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_DELIVERY_GROUP_ID = os.environ.get('TELEGRAM_DELIVERY_GROUP_ID', '')
TELEGRAM_ADMIN_ALERT_CHAT_ID = os.environ.get('TELEGRAM_ADMIN_ALERT_CHAT_ID', '')
TELEGRAM_API_TIMEOUT_SECONDS = int(os.environ.get('TELEGRAM_API_TIMEOUT_SECONDS', '10'))
TELEGRAM_CIRCUIT_FAILURE_THRESHOLD = int(os.environ.get('TELEGRAM_CIRCUIT_FAILURE_THRESHOLD', '3'))
TELEGRAM_CIRCUIT_OPEN_SECONDS = int(os.environ.get('TELEGRAM_CIRCUIT_OPEN_SECONDS', '180'))
TELEGRAM_CIRCUIT_REDIS_TIMEOUT_SECONDS = float(os.environ.get('TELEGRAM_CIRCUIT_REDIS_TIMEOUT_SECONDS', '0.2'))

REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', REDIS_URL)

CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_TASK_SOFT_TIME_LIMIT = 20 * 60
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', 'True' if DEBUG else 'False') == 'True'


WHATSAPP_WEBHOOK_VERIFY = os.environ.get('WHATSAPP_WEBHOOK_VERIFY', '')
WHATSAPP_INBOUND_RATE_LIMIT_WINDOW_SECONDS = int(
    os.environ.get('WHATSAPP_INBOUND_RATE_LIMIT_WINDOW_SECONDS', '60')
)
WHATSAPP_INBOUND_RATE_LIMIT_MAX = int(os.environ.get('WHATSAPP_INBOUND_RATE_LIMIT_MAX', '20'))
PRINT_JOB_STUCK_SECONDS = int(os.environ.get('PRINT_JOB_STUCK_SECONDS', '120'))
OUTBOX_STALE_SECONDS = int(os.environ.get('OUTBOX_STALE_SECONDS', '300'))
OUTBOX_PRIORITY_AGING_STEP_SECONDS = int(os.environ.get('OUTBOX_PRIORITY_AGING_STEP_SECONDS', '300'))
OUTBOX_PRIORITY_AGING_FACTOR = int(os.environ.get('OUTBOX_PRIORITY_AGING_FACTOR', '5'))
OUTBOX_SWEEP_FETCH_LIMIT = int(os.environ.get('OUTBOX_SWEEP_FETCH_LIMIT', '1000'))
OUTBOX_SWEEP_BATCH_SIZE = int(os.environ.get('OUTBOX_SWEEP_BATCH_SIZE', '200'))
IDEMPOTENCY_TTL_HOURS = int(os.environ.get('IDEMPOTENCY_TTL_HOURS', '24'))
PENDING_PAYMENT_TIMEOUT_SECONDS = int(os.environ.get('PENDING_PAYMENT_TIMEOUT_SECONDS', '600'))
PENDING_PAYMENT_REAPER_BATCH_SIZE = int(os.environ.get('PENDING_PAYMENT_REAPER_BATCH_SIZE', '50'))
MAX_OPEN_CASH_TURN_HOURS = int(os.environ.get('MAX_OPEN_CASH_TURN_HOURS', '20'))
IDEMPOTENCY_PURGE_AFTER_HOURS = int(os.environ.get('IDEMPOTENCY_PURGE_AFTER_HOURS', '168'))
IDEMPOTENCY_PURGE_BATCH_SIZE = int(os.environ.get('IDEMPOTENCY_PURGE_BATCH_SIZE', '1000'))
LEDGER_VERSION_FENCING_ENABLED = os.environ.get(
    'LEDGER_VERSION_FENCING_ENABLED',
    'False' if DEBUG else 'True',
) == 'True'
LEDGER_ACTIVATION_CACHE_TTL_SECONDS = int(os.environ.get('LEDGER_ACTIVATION_CACHE_TTL_SECONDS', '5'))
LEDGER_FENCED_MUTATION_PATHS = tuple(
    split_env_list(
        os.environ.get(
            'LEDGER_FENCED_MUTATION_PATHS',
            '/registrar_venta/,/api/reconciliar-pago/',
        )
    )
)
LEDGER_WEB_CLIENT_APP_VERSION = os.environ.get('LEDGER_WEB_CLIENT_APP_VERSION', 'pos-web')
POS_REPLAY_ADMISSION_ENABLED = os.environ.get(
    'POS_REPLAY_ADMISSION_ENABLED',
    'False' if DEBUG else 'True',
) == 'True'
POS_REPLAY_GLOBAL_SLOTS = int(os.environ.get('POS_REPLAY_GLOBAL_SLOTS', '8'))
POS_REPLAY_ORGANIZATION_SLOTS = int(os.environ.get('POS_REPLAY_ORGANIZATION_SLOTS', '1'))
POS_REPLAY_COLD_LANE_SLOTS = int(os.environ.get('POS_REPLAY_COLD_LANE_SLOTS', '2'))
POS_REPLAY_COLD_LANE_HOURS = int(os.environ.get('POS_REPLAY_COLD_LANE_HOURS', '48'))
POS_REPLAY_SLOT_TTL_SECONDS = int(os.environ.get('POS_REPLAY_SLOT_TTL_SECONDS', '15'))
POS_REPLAY_RETRY_AFTER_SECONDS = int(os.environ.get('POS_REPLAY_RETRY_AFTER_SECONDS', '5'))
OPS_PREFLIGHT_OPERATIONAL_DRIFT_LOOKBACK_HOURS = int(
    os.environ.get('OPS_PREFLIGHT_OPERATIONAL_DRIFT_LOOKBACK_HOURS', '72')
)
OPS_PREFLIGHT_REPLAY_ALERT_STALE_HOURS = int(
    os.environ.get('OPS_PREFLIGHT_REPLAY_ALERT_STALE_HOURS', '24')
)

# --- OPERACION / HORARIO ---
# En desarrollo se desactiva por defecto para facilitar pruebas.
# En produccion se activa por defecto.
ENABLE_BUSINESS_HOURS = os.environ.get('ENABLE_BUSINESS_HOURS', 'False' if DEBUG else 'True') == 'True'

