# Generated by Django 6.0.2 on 2026-02-14 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CajaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('base_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_final_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_efectivo_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_transferencia_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('origen', models.CharField(choices=[('POS', 'Local'), ('WEB', 'Web App')], default='POS', max_length=10)),
                ('cliente_nombre', models.CharField(default='Cliente Final', max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('comprobante_foto', models.ImageField(blank=True, null=True, upload_to='pagos/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Por Confirmar'), ('COCINA', 'En Cocina'), ('LISTO', 'Listo/Entregado')], default='PENDIENTE', max_length=20)),
                ('turno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='pos.cajaturno')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pos.venta')),
            ],
        ),
    ]
