# Generated by Django 6.0.2 on 2026-02-14 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_cliente_cajaturno_conteo_billetes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='horas_trabajadas',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cedula', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('pin', models.CharField(help_text='PIN de 4-6 dígitos', max_length=6, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('CAJERO', 'Cajero'), ('COCINA', 'Cocina'), ('MESERO', 'Mesero'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asistencia',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='pos.empleado'),
        ),
    ]
