# Generated by Django 6.0.2 on 2026-02-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_asistencia_horas_trabajadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='pin',
            field=models.CharField(help_text='PIN de 4 dígitos', max_length=4, unique=True),
        ),
    ]
