# Generated by Django 6.0.2 on 2026-02-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_empleado_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_pedido',
            field=models.CharField(choices=[('SERVIR', 'Para Servir'), ('LLEVAR', 'Para Llevar'), ('DOMICILIO', 'A Domicilio')], default='SERVIR', max_length=20),
        ),
    ]
