# Generated by Django 6.0.2 on 2026-02-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_venta_monto_recibido_venta_tipo_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='direccion_envio',
            field=models.TextField(blank=True, help_text='Dirección texto libre para domicilios'),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_cliente',
            field=models.CharField(blank=True, help_text='Teléfono del cliente para contacto', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Por Confirmar'), ('PENDIENTE_COTIZACION', 'Esperando Costo Envío'), ('COCINA', 'En Cocina'), ('LISTO', 'Listo/Entregado'), ('EN_CAMINO', 'En Camino'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=25),
        ),
    ]
