# Generated by Django 6.0.2 on 2026-02-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_venta_direccion_envio_venta_telefono_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ubicacion_lat',
            field=models.FloatField(blank=True, help_text='Latitud GPS del cliente', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='ubicacion_lng',
            field=models.FloatField(blank=True, help_text='Longitud GPS del cliente', null=True),
        ),
    ]
