# Generated by Django 6.0.2 on 2026-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_inventario_movimientocaja_movimientoinventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pago',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='APROBADO', max_length=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='referencia_pago',
            field=models.CharField(blank=True, help_text='Referencia/Lote/Aprobación de pago', max_length=40),
        ),
        migrations.AddField(
            model_name='venta',
            name='tarjeta_marca',
            field=models.CharField(blank=True, help_text='VISA, MASTERCARD, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='tarjeta_tipo',
            field=models.CharField(blank=True, help_text='CREDITO o DEBITO', max_length=12),
        ),
    ]
