# Generated by Django 6.0.2 on 2026-03-01 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_venta_estado_pago_venta_referencia_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], max_length=3)),
                ('telefono_e164', models.CharField(db_index=True, max_length=20)),
                ('message_sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='confirmacion_cliente',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada')], default='PENDIENTE', max_length=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='confirmada_por_bot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='delivery_quote_deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_cliente_e164',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pin',
            field=models.CharField(help_text='PIN de 4 digitos', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('CAJERO', 'Cajero'), ('COCINA', 'Cocina'), ('MESERO', 'Mesero'), ('DELIVERY', 'Delivery'), ('OTRO', 'Otro')], default='OTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Detalle libre: ej. Almuerzo 3 empleados', max_length=200),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='pin',
            field=models.CharField(help_text='Pin de 4-6 digitos para acceso POS', max_length=6),
        ),
        migrations.AlterField(
            model_name='venta',
            name='direccion_envio',
            field=models.TextField(blank=True, help_text='Direccion texto libre para domicilios'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Por Confirmar'), ('PENDIENTE_COTIZACION', 'Esperando Costo Envio'), ('COCINA', 'En Cocina'), ('LISTO', 'Listo/Entregado'), ('EN_CAMINO', 'En Camino'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=25),
        ),
        migrations.AlterField(
            model_name='venta',
            name='referencia_pago',
            field=models.CharField(blank=True, help_text='Referencia/Lote/Aprobacion de pago', max_length=40),
        ),
        migrations.AlterField(
            model_name='venta',
            name='telefono_cliente',
            field=models.CharField(blank=True, help_text='Telefono del cliente para contacto', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PROPUESTA', 'Propuesta'), ('GANADORA', 'Ganadora'), ('DESCARTADA', 'Descartada')], default='PROPUESTA', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_delivery', to='pos.empleado')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_quotes', to='pos.venta')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMANDA', 'Comanda'), ('TICKET', 'Ticket')], max_length=10)),
                ('estado', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('reintentos', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='pos.venta')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_e164', models.CharField(max_length=20, unique=True)),
                ('estado_flujo', models.CharField(choices=[('NUEVO', 'Nuevo'), ('LINK_ENVIADO', 'Link Enviado'), ('ESPERANDO_CONFIRMACION_TOTAL', 'Esperando Confirmacion Total'), ('FINALIZADO', 'Finalizado')], default='NUEVO', max_length=40)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('last_outbound_at', models.DateTimeField(blank=True, null=True)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_whatsapp', to='pos.venta')),
            ],
        ),
    ]
