# Generated by Django 6.0.2 on 2026-03-25 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_whatsappmessagelog_venta_confirmacion_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='repartidor_asignado',
            field=models.ForeignKey(blank=True, help_text='Repartidor que tomo el pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='pos.empleado'),
        ),
    ]
