# Generated by Django 6.0.2 on 2026-03-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_add_repartidor_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='salio_a_reparto_at',
            field=models.DateTimeField(blank=True, help_text='Momento en que el repartidor marco el pedido como EN_CAMINO.', null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tiempo_estimado_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo estimado restante informado por el repartidor cuando el pedido va en camino.', null=True),
        ),
    ]
