# Generated by Django 6.0.2 on 2026-04-01 00:24

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from zoneinfo import ZoneInfo

from django.contrib.auth.hashers import make_password
from django.conf import settings
from django.db import migrations, models


LEGACY_TO_V2_PAYMENT_STATUS = {
    'PENDIENTE': 'PENDING',
    'APROBADO': 'PAID',
    'RECHAZADO': 'FAILED',
    'ANULADO': 'VOIDED',
}


def _compute_operating_day(timestamp, timezone_name, operating_day_ends_at):
    if not timestamp:
        timestamp = django.utils.timezone.now()
    tz = ZoneInfo(timezone_name or 'America/Guayaquil')
    local_dt = django.utils.timezone.localtime(timestamp, tz)
    cutoff = operating_day_ends_at or datetime.time(4, 0)
    operating_day = local_dt.date()
    if local_dt.timetz().replace(tzinfo=None) < cutoff:
        operating_day -= datetime.timedelta(days=1)
    return operating_day


def _build_unique_alias(LocationAssignment, location, desired_alias):
    base = ''.join(ch for ch in (desired_alias or '').lower() if ch.isalnum())[:28] or 'staff'
    alias = base
    suffix = 1
    while LocationAssignment.objects.filter(location=location, alias_normalized=alias, active=True).exists():
        suffix += 1
        alias = f'{base[: max(1, 28 - len(str(suffix)))]}{suffix}'
    return alias


def bootstrap_v2_foundations(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    Organization = apps.get_model('pos', 'Organization')
    Location = apps.get_model('pos', 'Location')
    PersonProfile = apps.get_model('pos', 'PersonProfile')
    OrganizationMembership = apps.get_model('pos', 'OrganizationMembership')
    StaffProfile = apps.get_model('pos', 'StaffProfile')
    LocationAssignment = apps.get_model('pos', 'LocationAssignment')
    Empleado = apps.get_model('pos', 'Empleado')
    CajaTurno = apps.get_model('pos', 'CajaTurno')
    Venta = apps.get_model('pos', 'Venta')
    DetalleVenta = apps.get_model('pos', 'DetalleVenta')
    MovimientoCaja = apps.get_model('pos', 'MovimientoCaja')
    MovimientoInventario = apps.get_model('pos', 'MovimientoInventario')
    DeliveryQuote = apps.get_model('pos', 'DeliveryQuote')
    PrintJob = apps.get_model('pos', 'PrintJob')

    organization, _ = Organization.objects.get_or_create(
        slug='legacy-default',
        defaults={'name': 'Legacy Default Organization', 'active': True},
    )
    location, _ = Location.objects.get_or_create(
        organization=organization,
        slug='principal',
        defaults={
            'name': 'Principal',
            'timezone': 'America/Guayaquil',
            'operating_day_ends_at': datetime.time(4, 0),
            'active': True,
        },
    )

    for user in User.objects.all().iterator():
        legal_name = (f'{user.first_name} {user.last_name}'.strip() or user.username)
        PersonProfile.objects.get_or_create(
            user=user,
            defaults={'legal_name': legal_name},
        )

    for empleado in Empleado.objects.select_related('usuario').all().iterator():
        if not empleado.usuario_id:
            continue

        role = 'ADMIN' if empleado.rol == 'ADMIN' else 'STAFF'
        membership, _ = OrganizationMembership.objects.get_or_create(
            user_id=empleado.usuario_id,
            organization=organization,
            defaults={'role': role, 'active': True},
        )
        PersonProfile.objects.get_or_create(
            user_id=empleado.usuario_id,
            defaults={'legal_name': empleado.nombre or membership.user.username, 'cedula': empleado.cedula},
        )
        staff_profile, _ = StaffProfile.objects.get_or_create(
            membership=membership,
            defaults={
                'work_phone': empleado.telefono or '',
                'operational_role': empleado.rol or 'OTRO',
                'pin_hash': make_password(empleado.pin) if empleado.pin else '',
                'requires_pin_setup': False if empleado.pin else True,
                'active': empleado.activo,
            },
        )
        alias = _build_unique_alias(LocationAssignment, location, (empleado.nombre or membership.user.username).split()[0])
        LocationAssignment.objects.get_or_create(
            staff_profile=staff_profile,
            location=location,
            defaults={
                'alias': alias,
                'alias_normalized': alias.lower(),
                'active': empleado.activo,
            },
        )

    user_staff_by_user_id = {
        staff.membership.user_id: staff
        for staff in StaffProfile.objects.select_related('membership').all()
    }

    for caja in CajaTurno.objects.all().iterator():
        update_fields = []
        if not caja.organization_id:
            caja.organization_id = organization.id
            update_fields.append('organization')
        if not caja.location_id:
            caja.location_id = location.id
            update_fields.append('location')
        if not caja.timezone_snapshot:
            caja.timezone_snapshot = location.timezone
            update_fields.append('timezone_snapshot')
        if not caja.operating_day_ends_at_snapshot:
            caja.operating_day_ends_at_snapshot = location.operating_day_ends_at
            update_fields.append('operating_day_ends_at_snapshot')
        if not caja.operating_day:
            caja.operating_day = _compute_operating_day(
                caja.fecha_apertura,
                caja.timezone_snapshot,
                caja.operating_day_ends_at_snapshot,
            )
            update_fields.append('operating_day')
        if not caja.operator_opened_by_id and caja.usuario_id in user_staff_by_user_id:
            caja.operator_opened_by_id = user_staff_by_user_id[caja.usuario_id].id
            update_fields.append('operator_opened_by')
        if not caja.operator_closed_by_id and caja.fecha_cierre and caja.usuario_id in user_staff_by_user_id:
            caja.operator_closed_by_id = user_staff_by_user_id[caja.usuario_id].id
            update_fields.append('operator_closed_by')
        if update_fields:
            caja.save(update_fields=update_fields)

    turn_staff_by_turn_id = {
        caja.id: caja.operator_opened_by_id
        for caja in CajaTurno.objects.exclude(operator_opened_by_id__isnull=True).only('id', 'operator_opened_by_id')
    }

    for venta in Venta.objects.select_related('turno').all().iterator():
        update_fields = []
        resolved_location_id = venta.turno.location_id if venta.turno_id and venta.turno and venta.turno.location_id else location.id
        resolved_org_id = venta.turno.organization_id if venta.turno_id and venta.turno and venta.turno.organization_id else organization.id
        if not venta.location_id:
            venta.location_id = resolved_location_id
            update_fields.append('location')
        if not venta.organization_id:
            venta.organization_id = resolved_org_id
            update_fields.append('organization')
        if not venta.operating_day:
            if venta.turno_id and venta.turno and venta.turno.operating_day:
                venta.operating_day = venta.turno.operating_day
            else:
                venta.operating_day = _compute_operating_day(venta.fecha, location.timezone, location.operating_day_ends_at)
            update_fields.append('operating_day')
        if not venta.payment_status:
            venta.payment_status = LEGACY_TO_V2_PAYMENT_STATUS.get(venta.estado_pago, 'PAID')
            update_fields.append('payment_status')
        if not venta.payment_method_type and venta.metodo_pago:
            venta.payment_method_type = venta.metodo_pago
            update_fields.append('payment_method_type')
        if not venta.payment_reference and venta.referencia_pago:
            venta.payment_reference = venta.referencia_pago
            update_fields.append('payment_reference')
        if not venta.operator_id and venta.turno_id and turn_staff_by_turn_id.get(venta.turno_id):
            venta.operator_id = turn_staff_by_turn_id[venta.turno_id]
            update_fields.append('operator')
        if venta.operator_id and not venta.operator_display_name_snapshot:
            staff = user_staff_by_user_id.get(venta.turno.usuario_id) if venta.turno_id and venta.turno else None
            if staff:
                venta.operator_display_name_snapshot = staff.membership.user.username
                update_fields.append('operator_display_name_snapshot')
        if update_fields:
            venta.save(update_fields=update_fields)

    for detalle in DetalleVenta.objects.all().iterator():
        update_fields = []
        if not detalle.precio_bruto_unitario:
            detalle.precio_bruto_unitario = detalle.precio_unitario
            update_fields.append('precio_bruto_unitario')
        if not detalle.subtotal_neto:
            detalle.subtotal_neto = (detalle.precio_unitario * detalle.cantidad)
            update_fields.append('subtotal_neto')
        if update_fields:
            detalle.save(update_fields=update_fields)

    for movimiento in MovimientoCaja.objects.select_related('turno').all().iterator():
        update_fields = []
        if not movimiento.organization_id:
            movimiento.organization_id = movimiento.turno.organization_id if movimiento.turno_id and movimiento.turno.organization_id else organization.id
            update_fields.append('organization')
        if not movimiento.location_id:
            movimiento.location_id = movimiento.turno.location_id if movimiento.turno_id and movimiento.turno.location_id else location.id
            update_fields.append('location')
        if not movimiento.operator_id and movimiento.turno_id and turn_staff_by_turn_id.get(movimiento.turno_id):
            movimiento.operator_id = turn_staff_by_turn_id[movimiento.turno_id]
            update_fields.append('operator')
        if update_fields:
            movimiento.save(update_fields=update_fields)

    for movimiento in MovimientoInventario.objects.select_related('venta').all().iterator():
        update_fields = []
        if not movimiento.organization_id:
            movimiento.organization_id = movimiento.venta.organization_id if movimiento.venta_id and movimiento.venta.organization_id else organization.id
            update_fields.append('organization')
        if not movimiento.location_id:
            movimiento.location_id = movimiento.venta.location_id if movimiento.venta_id and movimiento.venta.location_id else location.id
            update_fields.append('location')
        if update_fields:
            movimiento.save(update_fields=update_fields)

    for quote in DeliveryQuote.objects.select_related('venta').all().iterator():
        update_fields = []
        if not quote.organization_id:
            quote.organization_id = quote.venta.organization_id if quote.venta_id and quote.venta.organization_id else organization.id
            update_fields.append('organization')
        if not quote.location_id:
            quote.location_id = quote.venta.location_id if quote.venta_id and quote.venta.location_id else location.id
            update_fields.append('location')
        if update_fields:
            quote.save(update_fields=update_fields)

    for job in PrintJob.objects.select_related('venta').all().iterator():
        update_fields = []
        if not job.organization_id:
            job.organization_id = job.venta.organization_id if job.venta_id and job.venta.organization_id else organization.id
            update_fields.append('organization')
        if not job.location_id:
            job.location_id = job.venta.location_id if job.venta_id and job.venta.location_id else location.id
            update_fields.append('location')
        if update_fields:
            job.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_venta_entrega_confirmada_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(default='America/Guayaquil', max_length=64)),
                ('operating_day_ends_at', models.TimeField(default=datetime.time(4, 0))),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='pos.organization')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='operating_day',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='operating_day_ends_at_snapshot',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='timezone_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='discount_rule_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='impuesto_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_bruto_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='pricing_rule_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='subtotal_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='tax_rule_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='authorization_reason_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='authorization_reason_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='pos.venta'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='venta',
            name='client_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='venta',
            name='operating_day',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='operator_display_name_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='venta',
            name='payment_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='payment_failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='payment_method_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='payment_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='venta',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='venta',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('FAILED', 'Fallido'), ('VOIDED', 'Anulado')], db_index=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='supervisor_display_name_snapshot',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_turns', to='pos.location'),
        ),
        migrations.AddField(
            model_name='deliveryquote',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_quotes', to='pos.location'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='pos.location'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='pos.location'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='pos.location'),
        ),
        migrations.AddField(
            model_name='venta',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pos.location'),
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_transaction_id', models.CharField(max_length=64)),
                ('request_fingerprint', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED_RETRYABLE', 'Failed Retryable'), ('FAILED_FINAL', 'Failed Final')], default='PENDING', max_length=32)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_records', to='pos.venta')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='pos.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='pos.organization')),
            ],
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_turns', to='pos.organization'),
        ),
        migrations.AddField(
            model_name='deliveryquote',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_quotes', to='pos.organization'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='pos.organization'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='pos.organization'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_jobs', to='pos.organization'),
        ),
        migrations.AddField(
            model_name='venta',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pos.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='pos.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=80)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('BLOCKED', 'Blocked')], db_index=True, default='PENDING', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='pos.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='pos.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_phone', models.CharField(blank=True, max_length=20)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('operational_role', models.CharField(choices=[('ADMIN', 'Administrador'), ('MANAGER', 'Manager'), ('CAJERO', 'Cajero'), ('COCINA', 'Cocina'), ('MESERO', 'Mesero'), ('DELIVERY', 'Delivery'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('pin_hash', models.CharField(blank=True, max_length=128)),
                ('pin_failed_attempts', models.PositiveIntegerField(default=0)),
                ('pin_blocked_until', models.DateTimeField(blank=True, null=True)),
                ('requires_pin_setup', models.BooleanField(default=True)),
                ('setup_token_hash', models.CharField(blank=True, max_length=128)),
                ('setup_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('setup_failed_attempts', models.PositiveIntegerField(default=0)),
                ('setup_blocked_until', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to='pos.organizationmembership')),
            ],
            options={
                'ordering': ['membership__organization__name', 'membership__user__username'],
            },
        ),
        migrations.CreateModel(
            name='LocationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=40)),
                ('alias_normalized', models.CharField(db_index=True, editable=False, max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='pos.location')),
                ('staff_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='pos.staffprofile')),
            ],
            options={
                'ordering': ['location__name', 'alias'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('target_model', models.CharField(max_length=80)),
                ('target_id', models.CharField(max_length=64)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pos.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='pos.organization')),
                ('actor_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pos.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='operator_closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cash_turns', to='pos.staffprofile'),
        ),
        migrations.AddField(
            model_name='cajaturno',
            name='operator_opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_turns', to='pos.staffprofile'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='pos.staffprofile'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_cash_movements', to='pos.staffprofile'),
        ),
        migrations.AddField(
            model_name='venta',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operated_sales', to='pos.staffprofile'),
        ),
        migrations.AddField(
            model_name='venta',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_sales', to='pos.staffprofile'),
        ),
        migrations.CreateModel(
            name='SupervisorAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_fingerprint', models.CharField(max_length=128)),
                ('reason_code', models.CharField(max_length=50)),
                ('reason_note', models.CharField(blank=True, max_length=255)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_authorizations', to='pos.location')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_authorizations', to='pos.staffprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_authorizations', to='pos.organization')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granted_authorizations', to='pos.staffprofile')),
            ],
            options={
                'ordering': ['-authorized_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5, help_text='Alerta cuando baje de esta cantidad')),
                ('unidad', models.CharField(default='unidades', help_text='Ej: unidades, libras, cajas', max_length=20)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='pos.location')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_inventory_items', to='pos.producto')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('location', 'producto'), name='uq_location_inventory_product')],
            },
        ),
        migrations.RunPython(bootstrap_v2_foundations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uq_location_slug_per_org'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['status', 'expires_at'], name='pos_idempot_status_ea3cc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('location', 'client_transaction_id'), name='uq_idempotency_location_client_transaction'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='uq_membership_user_org'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'available_at'], name='pos_outboxe_status_b5a855_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('location', 'alias_normalized'), name='uq_active_location_alias_normalized'),
        ),
    ]
