# Generated by Django 6.0.2 on 2026-04-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_backfill_sale_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='accounting_booked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='chronology_estimated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='client_created_at_raw',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='venta',
            name='client_monotonic_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='operated_at_normalized',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='queue_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='venta',
            name='session_seq_no',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
