# Generated by Django 6.0.2 on 2026-04-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_organization_ledger_shards'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOfflineOrphanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('client_transaction_id', models.CharField(db_index=True, max_length=64)),
                ('payment_reference', models.CharField(blank=True, max_length=80)),
                ('payment_provider', models.CharField(blank=True, max_length=50)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RESOLVED', 'Resuelto')], db_index=True, default='PENDING', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_offline_orphan_events', to='pos.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_offline_orphan_events', to='pos.organization')),
                ('resolved_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_pending_offline_orphans', to='pos.venta')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('event_type', 'client_transaction_id', 'payment_reference'), name='uq_pending_offline_orphan_event_pending')],
            },
        ),
    ]
