# Generated by Django 6.0.2 on 2026-04-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0029_pendingofflineorphanevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta/Medianet'), ('PAYPHONE', 'PayPhone')], max_length=20),
        ),
    ]
